### ISSUE TITLE
Excuse me, how to use these two tools to run

### ISSUE THREAD

**Issue by THEBEST-cloud** [GrimReaperSam/imagefusion_pytorch#1]
Can you tell me how to run this code using SPORCO and Pytorch？

**Comment by GrimReaperSam** [comment]
You should be able to `pip install` both sporco and pytorch and then you can use the code from Python.

**Comment by THEBEST-cloud** [comment]
Thank you, it has run successfully

**Comment by GrimReaperSam** [comment]
Solved
