### ISSUE TITLE
question

### ISSUE THREAD

**Issue by snow-dream-w** [GrimReaperSam/imagefusion_pytorch#2]
Excuse me , Would like to ask why there will be such a problem Cannot find reference 'tikhonov_filter' in 'util.py'

**Comment by GrimReaperSam** [comment]
You need to 'pip install sporco' to get that function

**Comment by snow-dream-w** [comment]
> You need to 'pip install sporco' to get that function

Thank you ,  This error will still be reported after installation.

**Comment by GrimReaperSam** [comment]
I'm sorry, which `util.py` file are you talking about?

**Comment by snow-dream-w** [comment]
sporco.util in the sporco program

**Comment by GrimReaperSam** [comment]
https://sporco.readthedocs.io/en/latest/modules/sporco.util.html#sporco.util.tikhonov_filter

It's there, are you sure you have the correct version of sporco?

**Comment by snow-dream-w** [comment]
through the link you provided, the version of sporco is 0.2.1b1, but when I tried installing this verion by the commands the link decribed, I have installed sporco with version 0.2.0. Version 0.2.0 has no function named tikhonov_filter in sporco.util. But the link you provided shows  verision 0.2.1b1 has this function. Can you provide a proper way for the installtion of V0.2.1b1? I will appreciate it if you provide any help.thank you! the attached link is V0.2.0
https://github.com/bwohlberg/sporco

**Comment by GrimReaperSam** [comment]
https://sporco.readthedocs.io/en/stable/modules/sporco.util.html#sporco.util.tikhonov_filter
These are the docs for the stable version: 0.2.0
It still has the function in sporco.util, if you look at the documentation it says it's being deprecated and points you to
`Function sporco.util.tikhonov_filter is deprecated; please use sporco.signal.tikhonov_filter instead.`
You could try that, feel free to make a PR here if it works for you.

**Comment by snow-dream-w** [comment]
Thank you very much. This problem has been solved

**Comment by GrimReaperSam** [comment]
Solved
